[package]
name = "tree_hash"
version = "0.1.1"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Efficient Merkle-hashing as used in Ethereum 2.0"

[[bench]]
name = "benches"
harness = false

[dev-dependencies]
criterion = "0.2"
rand = "0.7"
tree_hash_derive = "0.2"
types = { path = "../../types" }

[dependencies]
ethereum-types = "0.6"
eth2_hashing = "0.1"
lazy_static = "0.1"
