[package]
name = "cached_tree_hash"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>"]
edition = "2018"

[dev-dependencies]
tree_hash_derive = { path = "../tree_hash_derive" }

[dependencies]
tree_hash = "0.1"
ethereum-types = "0.5"
eth2_hashing = { path = "../eth2_hashing" }
int_to_bytes = { path = "../int_to_bytes" }
